live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#545454"
blue = "#94bff3"
cyan = "#93e0e3"
green = "#8ae234"
magenta = "#b294bb"
red = "#fc5454"
white = "#ffffff"
yellow = "#fce94f"

[colors.normal]
black = "#3f3f3f"
blue = "#94bff3"
cyan = "#06989a"
green = "#4e9a06"
magenta = "#85678f"
red = "#cc0000"
white = "#dcdccc"
yellow = "#c4a000"

[colors.primary]
background = "#222222"
foreground = "#F9F9F9"

[env]
TERM = "xterm-256color"

## Custom Font Config ##
[font]
size = 9.5

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0


## Default Font Config ##
# [font]
# size = 11.0

# [font.bold]
# family = "hack"
# style = "Bold"

# [font.bold_italic]
# family = "monospace"
# style = "Bold Italic"

# [font.italic]
# family = "hack"
# style = "Italic"

# [font.normal]
# family = "hack"
# style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[mouse]
hide_when_typing = true
bindings = [
{ mouse = "Right", action = "Paste" },
]

[scrolling]
history = 50000
multiplier = 3

[window]
dimensions = { columns = 110, lines = 30 }
# startup_mode = "Maximized"
opacity = 0.8
padding.x = 10
padding.y = 10

[cursor]
style.shape =  "Block"
style.blinking = "on"
unfocused_hollow = true

[shell]
program = "/bin/zsh"

[selection]
save_to_clipboard = true


